spring:
  datasource:
      url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false
      username: ${DB_USER}
      password: ${DB_PASS}
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE